services:
  - type: web
    name: mediafire-bot-webhook
    env: python
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
      - key: APP_URL
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
